In [1]:
import math
import pandas as pd
import numpy as np
from scipy.stats import norm, bernoulli, uniform, expon
from scenarios import *
from utils import *

In [2]:
seed = 0xC0FFEE
test_seed = 0xDECAF
n = 10_000

In [3]:
rng = np.random.default_rng(seed)


X1 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X2 = bernoulli.rvs(size=n, p=0.5, random_state=rng)
X3 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X4 = uniform.rvs(size=n, loc=-2, scale=4, random_state=rng)
X5 = expon.rvs(size=n, scale=1, random_state=rng)
X6 = rng.choice(['A','B','C'], size=n, p=[1/3]*3)
X7 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X8 = rng.choice(['0','1'], size=n, p=[1/2]*2)
X9 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)

eps_1 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
eps_4 = norm.rvs(size=n, loc=0, scale=2, random_state=rng)
eps_9 = norm.rvs(size=n, loc=0, scale=3, random_state=rng)

base_frame = pd.DataFrame(dict(
    X1=X1,
    X2=X2,
    X3=X3,
    X4=X4,
    X5=X5,
    X6=X6,
    X7=X7,
    X8=X8,
    X9=X9,
))

###
header("X1, X3, X7, X9 ~ N(0, 1)")
print(f"mean(X1) = {float(np.mean(X1)):.4f}; var(X1) = {float(np.var(X1)):.4f}")
print(f"mean(X3) = {float(np.mean(X3)):.4f}; var(X3) = {float(np.var(X3)):.4f}")
print(f"mean(X7) = {float(np.mean(X7)):.4f}; var(X7) = {float(np.var(X7)):.4f}")
print(f"mean(X9) = {float(np.mean(X9)):.4f}; var(X9) = {float(np.var(X9)):.4f}")
header("eps_1, eps_4, eps_9 ~ N(0, {1,4,9})")
print(f"mean(eps_1) = {float(np.mean(eps_1)):.4f}; var(eps_1) = {float(np.var(eps_1)):.4f}")
print(f"mean(eps_4) = {float(np.mean(eps_4)):.4f}; var(eps_4) = {float(np.var(eps_4)):.4f}")
print(f"mean(eps_9) = {float(np.mean(eps_9)):.4f}; var(eps_9) = {float(np.var(eps_9)):.4f}")
header("X2 ~ Bernoulli(0.5)")
print(f"mean(X2) = {float(np.mean(X2)):.4f}")
header("X4 ~ U(-2,2)")
print(f"mean(X4) = {float(np.mean(X4)):.4f}, min(X4) = {float(np.min(X4)):.4f}, max(X4) = {float(np.max(X4)):.4f}")
header("X5 ~ Exp(1)")
print(f"mean(X5) = {float(np.mean(X5)):.4f}")
header("X6 in {A, B, C}")
print(f"X6 == 'A': {np.mean(X6=='A')}; X6 == 'B': {np.mean(X6=='B')}; X6 == 'C': {np.mean(X6=='C')}")
header("X8 in {0, 1}")
print(f"X8=='0': {np.mean(X8 == '0')}; X8=='1': {np.mean(X8 == '1')}")

base_frame

X1, X3, X7, X9 ~ N(0, 1)
------------------------
mean(X1) = -0.0126; var(X1) = 1.0073
mean(X3) = 0.0001; var(X3) = 0.9880
mean(X7) = 0.0125; var(X7) = 1.0185
mean(X9) = -0.0053; var(X9) = 1.0044

eps_1, eps_4, eps_9 ~ N(0, {1,4,9})
-----------------------------------
mean(eps_1) = 0.0073; var(eps_1) = 1.0071
mean(eps_4) = 0.0442; var(eps_4) = 3.9979
mean(eps_9) = -0.0029; var(eps_9) = 9.0095

X2 ~ Bernoulli(0.5)
-------------------
mean(X2) = 0.5009

X4 ~ U(-2,2)
------------
mean(X4) = 0.0078, min(X4) = -1.9998, max(X4) = 2.0000

X5 ~ Exp(1)
-----------
mean(X5) = 1.0030

X6 in {A, B, C}
---------------
X6 == 'A': 0.3345; X6 == 'B': 0.3407; X6 == 'C': 0.3248

X8 in {0, 1}
------------
X8=='0': 0.5019; X8=='1': 0.4981

            X1  X2        X3        X4        X5 X6        X7 X8        X9
0     1.006644   1  0.635656 -1.095270  0.069668  B  0.446683  0  1.010124
1    -0.320191   1 -1.494756 -1.391787  1.907746  C -0.315841  1  0.088467
2     1.458234   1  0.067340  1.100860  0.368608  A  1.243192  1 -1.602867
3    -0.869859   0 -0.735143  0.005370  0.361992  B  0.223336  1 -0.716252
4     0.164425   1  0.779010 -1.913755  0.685403  C  0.259403  1  0.085351
...        ...  ..       ...       ...       ... ..       ... ..       ...
9995 -1.422990   1  0.846553  1.746577  1.212467  C -2.222187  1 -0.886820
9996  0.397753   0 -0.319677  1.191587  1.476849  C  0.708107  1 -0.338459
9997  2.845143   0  1.535575  1.903352  1.257166  C -0.924683  0  1.270026
9998 -0.323781   0  0.845329  0.599298  0.587658  A -0.998245  1 -1.312271
9999 -2.358195   1  1.064363 -0.004701  1.043625  B  0.177875  1 -0.224944

[10000 rows x 9 columns]

In [4]:
! cat -n scenarios.py

     1	import numpy as np
     2
     3	def gt_scenario_1(X1,X2,X3,X4,X5,X6,X7,X8,X9):
     4	    return 2.9*X1 - 3.7*X2+1.2*X3+0.8*X1*X1-1.5*X2*X3+1.1*X4-0.5*np.log(X5+1) + \
     5	           np.where(X6 == "B", 2, np.where(X6=="C", -1, 0)) + 0.3*X9
     6
     7	def gt_scenario_2(X1,X2,X3,X4,X5,X6,X7,X8,X9):
     8	    return np.sin(X1) + np.log(np.abs(X3)+1)+0.8*X4*X5 - 1.2*X1*X3 + np.where(X6 == "A", -2, np.where(X6=="C", 1, 0)) + \
     9	         1.5*X7+np.where(X8 == "1", 2, 0) + 0.4*X9*X9
    10
    11	def gt_scenario_3(X1,X2,X3,X4,X5,X6,X7,X8,X9):
    12	    def f(x):
    13	        return np.exp(np.cos(5*x*np.pi))
    14	    return f(X1) + 2*X2+0.5*np.exp(-(X3*X3))+0.7*np.sin(np.pi*X4)+0.6*X5**0.3+np.where(X6=='C',3,0)+\
    15	         0.9*X7+1.2*X9

In [5]:
Y_1_base = gt_scenario_1(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_1_1 = Y_1_base + eps_1
Y_1_4 = Y_1_base + eps_4
Y_1_9 = Y_1_base + eps_9

base_frame.assign(Y=Y_1_1).to_csv("data/synth_1_1.csv", index=False)
base_frame.assign(Y=Y_1_4).to_csv("data/synth_1_4.csv", index=False)
base_frame.assign(Y=Y_1_9).to_csv("data/synth_1_9.csv", index=False)

In [6]:
Y_2_base = gt_scenario_2(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_2_1 = Y_2_base + eps_1
Y_2_4 = Y_2_base + eps_4
Y_2_9 = Y_2_base + eps_9

base_frame.assign(Y=Y_2_1).to_csv("data/synth_2_1.csv", index=False)
base_frame.assign(Y=Y_2_4).to_csv("data/synth_2_4.csv", index=False)
base_frame.assign(Y=Y_2_9).to_csv("data/synth_2_9.csv", index=False)

In [7]:
Y_3_base = gt_scenario_3(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_3_1 = Y_3_base + eps_1
Y_3_4 = Y_3_base + eps_4
Y_3_9 = Y_3_base + eps_9

base_frame.assign(Y=Y_3_1).to_csv("data/synth_3_1.csv", index=False)
base_frame.assign(Y=Y_3_4).to_csv("data/synth_3_4.csv", index=False)
base_frame.assign(Y=Y_3_9).to_csv("data/synth_3_9.csv", index=False)

---
# Now let's generate the test data sets.

In [8]:
rng = np.random.default_rng(test_seed)

X1 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X2 = bernoulli.rvs(size=n, p=0.5, random_state=rng)
X3 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X4 = uniform.rvs(size=n, loc=-2, scale=4, random_state=rng)
X5 = expon.rvs(size=n, scale=1, random_state=rng)
X6 = rng.choice(['A','B','C'], size=n, p=[1/3]*3)
X7 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
X8 = rng.choice(['0','1'], size=n, p=[1/2]*2)
X9 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)

eps_1 = norm.rvs(size=n, loc=0, scale=1, random_state=rng)
eps_4 = norm.rvs(size=n, loc=0, scale=2, random_state=rng)
eps_9 = norm.rvs(size=n, loc=0, scale=3, random_state=rng)

base_frame = pd.DataFrame(dict(
    X1=X1,
    X2=X2,
    X3=X3,
    X4=X4,
    X5=X5,
    X6=X6,
    X7=X7,
    X8=X8,
    X9=X9,
))

###
header("X1, X3, X7, X9 ~ N(0, 1)")
print(f"mean(X1) = {float(np.mean(X1)):.4f}; var(X1) = {float(np.var(X1)):.4f}")
print(f"mean(X3) = {float(np.mean(X3)):.4f}; var(X3) = {float(np.var(X3)):.4f}")
print(f"mean(X7) = {float(np.mean(X7)):.4f}; var(X7) = {float(np.var(X7)):.4f}")
print(f"mean(X9) = {float(np.mean(X9)):.4f}; var(X9) = {float(np.var(X9)):.4f}")
header("eps_1, eps_4, eps_9 ~ N(0, {1,4,9})")
print(f"mean(eps_1) = {float(np.mean(eps_1)):.4f}; var(eps_1) = {float(np.var(eps_1)):.4f}")
print(f"mean(eps_4) = {float(np.mean(eps_4)):.4f}; var(eps_4) = {float(np.var(eps_4)):.4f}")
print(f"mean(eps_9) = {float(np.mean(eps_9)):.4f}; var(eps_9) = {float(np.var(eps_9)):.4f}")
header("X2 ~ Bernoulli(0.5)")
print(f"mean(X2) = {float(np.mean(X2)):.4f}")
header("X4 ~ U(-2,2)")
print(f"mean(X4) = {float(np.mean(X4)):.4f}, min(X4) = {float(np.min(X4)):.4f}, max(X4) = {float(np.max(X4)):.4f}")
header("X5 ~ Exp(1)")
print(f"mean(X5) = {float(np.mean(X5)):.4f}")
header("X6 in {A, B, C}")
print(f"X6 == 'A': {np.mean(X6=='A')}; X6 == 'B': {np.mean(X6=='B')}; X6 == 'C': {np.mean(X6=='C')}")
header("X8 in {0, 1}")
print(f"X8=='0': {np.mean(X8 == '0')}; X8=='1': {np.mean(X8 == '1')}")

base_frame

X1, X3, X7, X9 ~ N(0, 1)
------------------------
mean(X1) = 0.0049; var(X1) = 1.0134
mean(X3) = 0.0069; var(X3) = 1.0001
mean(X7) = -0.0000; var(X7) = 0.9774
mean(X9) = -0.0029; var(X9) = 1.0144

eps_1, eps_4, eps_9 ~ N(0, {1,4,9})
-----------------------------------
mean(eps_1) = -0.0032; var(eps_1) = 1.0204
mean(eps_4) = 0.0189; var(eps_4) = 3.8595
mean(eps_9) = 0.0095; var(eps_9) = 9.0403

X2 ~ Bernoulli(0.5)
-------------------
mean(X2) = 0.5027

X4 ~ U(-2,2)
------------
mean(X4) = 0.0044, min(X4) = -1.9999, max(X4) = 1.9999

X5 ~ Exp(1)
-----------
mean(X5) = 0.9866

X6 in {A, B, C}
---------------
X6 == 'A': 0.3344; X6 == 'B': 0.3264; X6 == 'C': 0.3392

X8 in {0, 1}
------------
X8=='0': 0.4921; X8=='1': 0.5079

            X1  X2        X3        X4        X5 X6        X7 X8        X9
0    -0.228094   1  0.345300 -0.634083  0.652985  B  0.071964  0 -0.738266
1     0.856018   0 -0.285141  1.830076  2.568996  C -0.259826  0  1.673823
2    -0.895550   0  0.674903 -0.603188  0.908621  B  1.625733  1 -0.935931
3     1.251419   1 -1.065272 -0.353580  1.459015  B  1.337724  1 -0.448277
4     0.752532   0 -1.184312  1.560610  0.198151  A  0.268610  0 -0.617399
...        ...  ..       ...       ...       ... ..       ... ..       ...
9995  0.065433   0  0.253233  1.616314  0.092226  B -0.521941  1  0.236529
9996 -0.336221   1 -0.861732 -0.770251  0.022056  C -0.809979  1  0.672077
9997  1.125066   1  0.239114 -0.536340  1.049636  A  0.452918  1  0.506271
9998 -0.758117   0 -0.423431  1.390906  0.694763  C -0.564094  1  1.224939
9999  0.669995   1 -0.365789  0.756962  0.863485  A -0.898921  0 -1.650441

[10000 rows x 9 columns]

In [9]:
Y_1_base = gt_scenario_1(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_1_1 = Y_1_base + eps_1
Y_1_4 = Y_1_base + eps_4
Y_1_9 = Y_1_base + eps_9

base_frame.assign(Y=Y_1_1).to_csv("data/test_synth_1_1.csv", index=False)
base_frame.assign(Y=Y_1_4).to_csv("data/test_synth_1_4.csv", index=False)
base_frame.assign(Y=Y_1_9).to_csv("data/test_synth_1_9.csv", index=False)

In [10]:
Y_2_base = gt_scenario_2(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_2_1 = Y_2_base + eps_1
Y_2_4 = Y_2_base + eps_4
Y_2_9 = Y_2_base + eps_9

base_frame.assign(Y=Y_2_1).to_csv("data/test_synth_2_1.csv", index=False)
base_frame.assign(Y=Y_2_4).to_csv("data/test_synth_2_4.csv", index=False)
base_frame.assign(Y=Y_2_9).to_csv("data/test_synth_2_9.csv", index=False)

In [11]:
Y_3_base = gt_scenario_3(X1,X2,X3,X4,X5,X6,X7,X8,X9)

Y_3_1 = Y_3_base + eps_1
Y_3_4 = Y_3_base + eps_4
Y_3_9 = Y_3_base + eps_9

base_frame.assign(Y=Y_3_1).to_csv("data/test_synth_3_1.csv", index=False)
base_frame.assign(Y=Y_3_4).to_csv("data/test_synth_3_4.csv", index=False)
base_frame.assign(Y=Y_3_9).to_csv("data/test_synth_3_9.csv", index=False)